[toolchain]

[features]
seeds = false
skip-lint = true

[programs.devnet]
caelum_amm = "7uTEXZNdMUkjBmN5LvhN7iZ56WsgoW5PjTDBgGvqiFMT"
nft-conversion = "HQMM3aYxwgV7wtNwWzx34ALb7psP4NRsygp7eZ7hoABv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/artimus100/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
